spring:
  application:
    name: ms-notificaciones
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:turismo_user}
    password: ${RABBITMQ_PASSWORD:turismo_password}

app:
  rabbitmq:
    exchange: ${RABBITMQ_EXCHANGE:turismo.exchange}
    reservas:
      queue: ${RABBITMQ_RESERVAS_QUEUE:cola.reservas}
      routing-key: ${RABBITMQ_RESERVAS_ROUTING_KEY:reserva.creada}
    pagos:
      queue: ${RABBITMQ_PAGOS_QUEUE:cola.pagos}
      routing-key: ${RABBITMQ_PAGOS_ROUTING_KEY:pago.confirmado}

server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    enabled: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
