spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ms-paquetes-route
          uri: lb://ms-paquetes
          predicates:
            - Path=/api/paquetes/**
        - id: ms-usuarios-route
          uri: lb://ms-usuarios
          predicates:
            - Path=/api/usuarios/**
        - id: ms-usuarios-clientes-route
          uri: lb://ms-usuarios
          predicates:
            - Path=/api/clientes/**
        - id: ms-reservas-route
          uri: lb://ms-reservas
          predicates:
            - Path=/api/reservas/**
        - id: ms-pagos-route
          uri: lb://ms-pagos
          predicates:
            - Path=/api/pagos/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    enabled: true
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
